### PR TITLE
findvortices_interp no longer returns only first interpolated vortex

### PR DESCRIPTION
**Pull request by mcawte**

### CODE REVIEW

**Comment by AshtonSBradley** [comment]
Can you say a bit about what the problem is, and how this fixes it?

**Comment by mcawte** [comment]
The problem is that "return vort" breaks out of the try catch loop after only using corezoom on the first vortex. By moving "return vort" to outside of the try catch loop, but still inside the function, all the vortices have corezoom evaluated.

**Comment by mcawte** [comment]
This way works fine:

```
Julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.3.1 (2019-12-30)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(v1.3) pkg> status
    Status `~/.julia/environments/v1.3/Project.toml`
  [621f4979] AbstractFFTs v0.5.0
  [537997a7] AbstractPlotting v0.9.16
  [c52e3926] Atom v0.11.3
  [6e4b80f9] BenchmarkTools v0.4.3
  [5ae59095] Colors v0.11.1
  [717857b8] DSP v0.6.2
  [a93c6f00] DataFrames v0.20.0
  [0c46a032] DifferentialEquations v6.9.0
  [b4f34e82] Distances v0.8.2
  [7a1cc6ca] FFTW v1.2.0
  [057dd010] FastTransforms v0.8.2
  [5789e2e9] FileIO v1.2.1
  [53c48c17] FixedPointNumbers v0.6.1
  [f013a474] FourierGPE v0.1.0 #master (https://github.com/AshtonSBradley/FourierGPE.jl.git)
  [60bf3e95] GLPK v0.12.1
  [c43c736e] Genie v0.22.9
  [7073ff75] IJulia v1.20.2
  [6218d12a] ImageMagick v1.1.1
  [02fcd773] ImageTransformations v0.8.1
  [916415d5] Images v0.19.3
  [a98d9a8b] Interpolations v0.12.5
  [033835bb] JLD2 v0.1.10
  [4076af6c] JuMP v0.20.1
  [e5e0dc1b] Juno v0.7.2
  [b964fa9f] LaTeXStrings v1.0.3
  [ee78f7c6] Makie v0.9.5
  [91a5bcdd] Plots v0.28.4
  [dca85d43] QuartzImageIO v0.6.0
  [295af30f] Revise v2.5.0
  [b688e990] VortexDistributions v0.0.0 #master (https://github.com/AshtonSBradley/VortexDistributions.jl.git)

julia> using VortexDistributions
julia> x = LinRange(-128,127.5,256); y = LinRange(-128,127.5,256); 
julia> ψ0 = ones(256,256) |> complex;
julia> ψ = Torus(ψ0,x,y)
Torus
  ψ: Array{Complex{Float64}}((256, 256)) Complex{Float64}[1.0 + 0.0im 1.0 + 0.0im … 1.0 + 0.0im 1.0 + 0.0im; 1.0 + 0.0im 1.0 + 0.0im … 1.0 + 0.0im 1.0 + 0.0im; … ; 1.0 + 0.0im 1.0 + 0.0im … 1.0 + 0.0im 1.0 + 0.0im; 1.0 + 0.0im 1.0 + 0.0im … 1.0 + 0.0im 1.0 + 0.0im]
  x: Array{Float64}((256,)) [-128.0, -126.99803921568628, -125.99607843137255, -124.99411764705883, -123.9921568627451, -122.99019607843137, -121.98823529411764, -120.98627450980392, -119.9843137254902, -118.98235294117647  …  118.48235294117647, 119.4843137254902, 120.48627450980392, 121.48823529411764, 122.49019607843137, 123.49215686274509, 124.49411764705883, 125.49607843137255, 126.49803921568628, 127.5]
  y: Array{Float64}((256,)) [-128.0, -126.99803921568628, -125.99607843137255, -124.99411764705883, -123.9921568627451, -122.99019607843137, -121.98823529411764, -120.98627450980392, -119.9843137254902, -118.98235294117647  …  118.48235294117647, 119.4843137254902, 120.48627450980392, 121.48823529411764, 122.49019607843137, 123.49215686274509, 124.49411764705883, 125.49607843137255, 126.49803921568628, 127.5]

julia> v1 = PointVortex(5,0.34,1); v2 = PointVortex(-30,44.863,-1); v3 = PointVortex(40,-6.434,-1);
julia> vortex!(ψ,[v1,v2,v3])
julia> findvortices(ψ)
3-element Array{PointVortex,1}:
 PointVortex(-30.01937686469069, 44.85961872879046, -1)
 PointVortex(4.759803921568633, 0.7519607843137237, 1)
 PointVortex(39.82843137254902, -6.261764705882342, -1)
```

Whereas something a bit more traditional gives grief 

```
julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.3.1 (2019-12-30)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using VortexDistributions
julia> Lx = 128; Ly = Lx; R = 45; Res = 2; ξ = 1;
julia> Mx = Res*Lx; My = Mx;
julia>  x = LinRange(-Lx/2,Lx/2,Mx+1);
julia>  y = LinRange(-Ly/2,Ly/2,My+1);
julia>  x = x[1:end-1];
julia>  y = transpose(y[1:end-1]);
julia> N = 6;
Vortex = [30*exp(1im*2π*(n-1)/N)  for n = 1:N]
6-element Array{Complex{Float64},1}:
                30.0 + 0.0im
  15.000000000000004 + 25.980762113533157im
 -14.999999999999993 + 25.98076211353316im
               -30.0 + 3.67394039744206e-15im
 -15.000000000000014 - 25.980762113533153im
  15.000000000000004 - 25.980762113533157im
julia> V = -5 .*[(tanh.((sqrt((x)^2 + (y)^2)-R)).^6-1)  for x in x, y in y'];
julia> Rgrid = [r = sqrt((x)^2 + (y)^2) for x in x, y in y'];
julia> V[Rgrid .>R] .= 5

julia> yy,psi = load("core_density.jld2","y","psi"); # Cheating here. This is the density profile of a vortex

julia> knots=(yy,);

julia> itpξ = interpolate(knots.*ξ,psi,Gridded(Linear()));

julia> V1 = zeros(length(x),length(y),N);

julia> r1 = [sqrt.((y.*ones(length(x)).-imag(Vortex[i])).^2 + (x.*ones(length(y))'.-real(Vortex[i])).^2) for i = 1:N];

julia> ψ0 = complex.(sqrt.((10)*max.(0,1 .-V)));

julia> for i = 1:N
V1[:,:,i] = itpξ.(r1[i])
end
ψp = V1[:,:,1].*ψ0
for i = 2:N
ψp[:,:] = ψp[:,:].*V1[:,:,i]
end

julia> phase = zeros(length(x),length(y))
julia> for i = 1:N
   phase[:,:] .+= (-1)^(i+1).*atan.(y.*ones(length(x)).-imag(Vortex[i]),x.*ones(length(y))'.-real(Vortex[i])) 
end

julia> for i = 1:N
   phase[:,:] .+= (-1)^(i).*atan.(y.*ones(length(x)).-imag(R^2 ./conj.(Vortex[i])),x.*ones(length(y))'.-real(R^2 ./conj.(Vortex[i]))) 
end

julia> ψ =  ψp.*exp.(1im*phase);

julia> psi = Torus(ψ,x,y')
Torus
  ψ: Array{Complex{Float64}}((256, 256)) Complex{Float64}[0.0 + 0.0im 0.0 + 0.0im … 0.0 + 0.0im 0.0 + 0.0im; 0.0 + 0.0im 0.0 + 0.0im … 0.0 + 0.0im 0.0 + 0.0im; … ; 0.0 + 0.0im 0.0 + 0.0im … 0.0 + 0.0im 0.0 + 0.0im; 0.0 + 0.0im 0.0 + 0.0im … 0.0 + 0.0im 0.0 + 0.0im]
  x: Array{Float64}((256,)) [-64.0, -63.5, -63.0, -62.5, -62.0, -61.5, -61.0, -60.5, -60.0, -59.5  …  59.0, 59.5, 60.0, 60.5, 60.99999999999999, 61.49999999999999, 62.00000000000001, 62.5, 63.0, 63.5]
  y: Array{Float64}((256,)) [-64.0, -63.5, -63.0, -62.5, -62.0, -61.5, -61.0, -60.5, -60.0, -59.5  …  59.0, 59.5, 60.0, 60.5, 60.99999999999999, 61.49999999999999, 62.00000000000001, 62.5, 63.0, 63.5]

julia> findvortices(psi)
12-element Array{PointVortex,1}:
 PointVortex(-43.25, 0.25, 1)
 PointVortex(-29.750000000000007, 0.25, -1)
 PointVortex(-21.750000000000007, 37.24999999999999, -1)
 PointVortex(-21.249999999999996, -37.25, -1)
 PointVortex(-15.25, -25.75, 1)
 PointVortex(-15.25, 25.750000000000007, 1)
 PointVortex(15.25, -25.75, -1)
 PointVortex(15.25, 25.750000000000007, -1)
 PointVortex(21.249999999999993, -37.25, 1)
 PointVortex(21.750000000000007, 37.24999999999999, 1)
 PointVortex(29.750000000000007, 0.25, 1)
 PointVortex(43.25, -0.25, -1)

julia> findvortices(psi,true)
12-element Array{PointVortex,1}:
 PointVortex(-43.25, 0.25, 1)
 PointVortex(-29.750000000000007, 0.25, -1)
 PointVortex(-21.750000000000007, 37.24999999999999, -1)
 PointVortex(-21.249999999999996, -37.25, -1)
 PointVortex(-15.25, -25.75, 1)
 PointVortex(-15.25, 25.750000000000007, 1)
 PointVortex(15.25, -25.75, -1)
 PointVortex(15.25, 25.750000000000007, -1)
 PointVortex(21.249999999999993, -37.25, 1)
 PointVortex(21.750000000000007, 37.24999999999999, 1)
 PointVortex(29.750000000000007, 0.25, 1)
 PointVortex(43.25, -0.25, -1)
```

As you can see the findvortices function now only returns vortex positions on the grid points. Now I import the relevant methods, and show the result when applying my pull request:

```
julia> import VortexDistributions.findvortices
julia> import VortexDistributions.findvortices_jumps
julia> import VortexDistributions.removeedgevortices
julia> import VortexDistributions.corezoom

julia> findvortices_interp(psi)
12-element Array{PointVortex,1}:
 PointVortex(-43.25, 0.25, 1)
 PointVortex(-29.750000000000007, 0.25, -1)
 PointVortex(-21.750000000000007, 37.24999999999999, -1)
 PointVortex(-21.249999999999996, -37.25, -1)
 PointVortex(-15.25, -25.75, 1)
 PointVortex(-15.25, 25.750000000000007, 1)
 PointVortex(15.25, -25.75, -1)
 PointVortex(15.25, 25.750000000000007, -1)
 PointVortex(21.249999999999993, -37.25, 1)
 PointVortex(21.750000000000007, 37.24999999999999, 1)
 PointVortex(29.750000000000007, 0.25, 1)
 PointVortex(43.25, -0.25, -1)

# Redefine the function

julia> function findvortices_interp(psi::Field)
           vort = findvortices_grid(psi,shift=true)
           vort = removeedgevortices(vort,psi)
           #TODO: allow for interp with periodic data (here edges are stripped)

           for (j,vortex) in enumerate(vort)
               try
               vortz,psiz = corezoom(vortex,psi)
               vortz,psiz = corezoom(vortz,psiz)
               vortz,psiz = corezoom(vortz,psiz)
               vort[j] = vortz
               catch nothing
               end
           end
           return vort
       end

julia> findvortices_interp(psi)
12-element Array{PointVortex,1}:
 PointVortex(-43.25, 0.25, 1)
 PointVortex(-29.999856492681126, 0.0003895198655107391, -1)
 PointVortex(-21.750000000000007, 37.24999999999999, -1)
 PointVortex(-21.249999999999996, -37.25, -1)
 PointVortex(-14.999589979088935, -25.979314445036696, 1)
 PointVortex(-15.25, 25.750000000000007, 1)
 PointVortex(15.000512526138838, -25.979314445036696, -1)
 PointVortex(15.25, 25.750000000000007, -1)
 PointVortex(21.249999999999993, -37.25, 1)
 PointVortex(21.51920947968346, 37.53645085899382, 1)
 PointVortex(30.000102505227773, 0.0003895198655107391, 1)
 PointVortex(43.53823444995695, 0.00010250522776776095, -1)
```

Now corezoom is actually working. I do not yet understand why my field has this issue and yet the first example does not.

Edit - Looking at this now, the results are not even on the grid points originally. The grid points are in increments of 0.5, not 0.25. The pull request seemed to get this package to agree with my old method of finding vortices last night. But this example shows I don't understand what is happening. I need some more time to test this.

**Comment by AshtonSBradley** [comment]
Looks good, thanks!

**Pull request merged**
